# fly.toml file generated for fake-slack on 2023-05-06T08:51:41-04:00

app = "fake-slack"
kill_signal = "SIGTERM"
kill_timeout = 5
primary_region = "yyz"
processes = []

[build]

[env]

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 5000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
  handlers = []
  port = "5000"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
